apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aws-agent.fullname" . }}
  labels:
    {{- include "aws-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "aws-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '{{ .Values.port }}'
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aws-agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aws-agent.serviceAccountName" . }}
      priorityClassName: {{ .Values.priorityClassName }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AWS_REGION
              value: {{ .Values.aws.region }}
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.aws.key }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.aws.secret }}
            - name: RDS_DB_USER
              value: {{ .Values.rds.user }}
            - name: RDS_DB_PASSWORD
              value: {{ .Values.rds.password }}
            - name: RDS_FILTER
              value: {{ .Values.rds.filter }}
            - name: EC_FILTER
              value: {{ .Values.ec.filter }}
            - name: LISTEN_ADDRESS
              value: ":{{ .Values.port }}"
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
